name: mit_flutter_plugin
description: "MIT Map services plugin for flutter."
version: 1.0.0
homepage: https://metaindonesia.technology

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: '>=3.22.0'

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  package_info_plus: ^8.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
        podspec: ios/mit_flutter_plugin.podspec
        

